development:
  adapter: postgresql
  database: crowdfunder_development
  host: localhost
  user: postgres
  password: pg

test:
  adapter: postgresql
  database: crowdfunder_test
  host: localhost
  user: postgres
  password: pg
